version: 2
jobs:
  publish:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Check Tagged Push
          command: |
            TAG_VERSION=$(git tag -l --sort=-v:refname | head -n 1 | cut -d'-' -f2)
            PKG_VERSION=$(cat logdna/_version.py | grep "__version__ = " | cut -d'=' -f2 | cut -d"'" -f2)
            if [[ "${TAG_VERSION}" != "${PKG_VERSION}" ]]; then
              echo "There is mismatch:"
              echo "  TAG_VERSION: ${TAG_VERSION}"
              echo "  PKG_VERSION: ${PKG_VERSION}"
              exit 1
            fi
      - run:
          name: Publish
          command: |
            sudo pip install twine
            sudo pip3 install twine
            python setup.py sdist
            twine upload dist/*.tar.gz
workflows:
  version: 2
  update_package:
    jobs:
      - publish:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?/
            branches:
              ignore: /.*/
